filetype plugin indent on
syntax on

set nu
set path+=**
set shiftwidth=4
set tabstop=4
set softtabstop=4
set et
set incsearch
set hlsearch
set scrolloff=10
set listchars=tab:>~,nbsp:_,trail:-
set noswapfile
set wildmenu
set termguicolors

let g:mapleader = " "
nnoremap <leader>sf :find<SPACE>
nnoremap <leader>sg :Grep<SPACE>
nnoremap <silent><Esc> :nohlsearch<CR>
nnoremap <C-c> :cnext<CR>
nnoremap <C-k> :cprev<CR>
nnoremap <leader>n :Ex<CR>
nnoremap <leader>p <C-^>

if executable("rg")
    set grepprg=rg\ --vimgrep\ --no-heading
endif
set grepformat=%f:%l:%c%m
command! -nargs=+ -complete=file -bar Grep silent grep <args>|cope|redraw!
